default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - --strict
          - feat
          - fix
          - chore
          - docs
          - refactor
          - test
          - ci
          - build
          - wip
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        name: ruff lint + fix
        stages: [pre-commit]
        args:
          - --fix
          - --select=E,F,B,UP,I,SIM
          - --line-length=100

      - id: ruff-format
        name: ruff format
        stages: [pre-commit]
        args:
          - --line-length=100
  - repo: local
    hooks:
      - id: compile-requirements
        name: compile requirements.txt
        entry: ./compile_requirements.sh
        language: system
        files: ^requirements\.in$
        pass_filenames: false
        stages: [pre-commit]
